/*
 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    "[10x1] That Upgrade.": "[10x1] 那个升级.",

    "[1x1] Glitch gain x2.": "[1x1] 故障获取量 x2.",
    "[1x1] Glitches gained on last reset boosts point gain.": "[1x1] 上一轮获得的故障加成点数获取.",

    "[1x2] Improves Glitch gain by 1.4x.": "[1x2] 故障获取 x1.4.",
    "[1x2] You get a System reset once you buy THAT upgrade. (No timewalls! Yay!": "[1x2] 当你获得“那个升级”时,立刻进行一次系统重置.(没时间墙了! 耶!",

    "[1x3] Cracks production interval decreases from 10 to 6.": "[1x3] 裂隙生产间隔从10次点击减短到6次点击.",
    "[1x3] Reality doesn't reset anything & doesn't pop up that quirky window.": "[1x3] 现实不再重置任何东西 & 不再显示那个奇怪的重置画面.",

    "[1x4] LoC gain x3.": "[1x4] 代码行获取量 x3.",
    "[1x4] You start each Glitch reset with a Crack.": "[1x4] 你在每轮故障重置开始时获得一个裂隙.",

    "[2x1] Gain 3x Points on the first 3 clicks of every run.": "[2x1] 每轮的前三次点击获得3倍点数.",
    "[2x1] Glitch gain x3.": "[2x1] 故障获取量 x3.",

    "[2x2] Keep all Page 1 Glitch Upgrades on System reset.": "[2x2] 系统重置时保留所有第一页的故障升级.",
    "[2x2] When you buy something, you get free Points equal to 15% of click power.": "[2x2] 当你点击购买的时候, 你获得点击产生的15%点数.",

    "[2x3] Void Tears are auto-bought if you have remaining clicks, and you gain 100% of the points gained on buying stuff.": "[2x3] 虚空裂口在你还能点击时会被自动购买, 并且买东西时获得100%的点击产生的点数.",
    "[2x3] Void Tears are marginally cheaper.": "[2x3] 虚空裂口价格略微降低.",

    "[2x4] LoC gain x3.": "[2x4] 代码行获取量 x3.",
    "[2x4] Unlock the ability to buy two Faults once at the cost of 30 Points.": "[2x4] 解锁用30点数一次性买两个错误的能力.",//卖竹鼠啦,三块钱一个,十块钱三个!

    "[3x1] Glitch gain x4.": "[3x1] 故障获取量 x4.",
    "[3x1] Willpower affects Points gain with greatly reduced effect.": "[3x1] 意志力以大幅削弱的效果增幅点数获取.",

    "[3x2] Keep all Page 2 Glitch Upgrades on System reset and Challenges completed.": "[3x2] 系统重置时保留所有第二页的故障升级和所有挑战.",
    "[3x2] When you buy something, you get extra free Points equal to 15% of click power.": "[3x2] 当你点击购买时, 你额外获得点击产生的15%点数.",

    "[3x3] Start with Malfunctioning reality already done, and Glitch Power Generators are auto-bought.": "[3x3] 以失灵现实开局, 并且自动化故障能量发生器.",
    "[3x3] Willpower's effect on Glitches is better.": "[3x3] 意志力对故障获取量的加成更强.",

    "[3x4] LoC gain x3.": "[3x4] 代码获取量 x3.",
    "[3x4] Unlock the ability to buy two Cracks once at the cost of 30 Faults.": "[3x4] 解锁用30个错误一次性购买2个裂隙的能力.",

    "[4x1] Gain 5x Points on the last 5 clicks of every run.": "[4x1] 最后5次点击获得5x点数.",
    "[4x1] Glitch gain ^1.05.": "[4x1] 故障获取量 ^1.05.",

    "[4x2] Keep all Glitch Upgrades on System reset and Goals completed.": "[4x2] 系统重置时保留所有故障升级和达成的目标.",
    "[4x2] Raise Glitch gain to the power of ^1.10. (Before softcap": "[4x2] 故障获取量 ^1.10. (在软上限前生效",

    "[4x3] Cracks, Loopholes and Eradications costs are decreased from 10 to 2.": "[4x3] 裂隙, 漏洞, 根除价格从10降至2.",
    "[4x3] Start in Florena's Reality.": "[4x3] 以芙雷娜的现实开局.",

    "[4x4] LoC gain x3.": "[4x4] 代码行获取量 x3.",
    "[4x4] Unlocks Challenges.": "[4x4] 解锁挑战.",

    "[5x1] Glitch Upgrade 1x1 effect is raised. (^1.6": "[5x1] 增幅故障升级1x1的效果. (^1.6",

    "[5x2] Unlocks the Glitch Power Generator.": "[5x2] 解锁故障能量发生器.",

    "[5x3] Increases Glitch Power Generators' multiplier per purchase. (x4 -> x6": "[5x3] 提高故障能量发生器的购买倍率. (x4 -> x6",

    "[5x4] Decreases Glitch Power Generators' cost scaling.": "[5x4] 减缓故障能量发生器的价格增长.",

    "[6x1] Glitch Power is no longer reset on Glitch reset.": "[6x1] 故障重置不再重置故障能量.",

    "[6x2] You gain 1.5x more Void Tears from Glitch Power.": "[6x2] 故障能量产生的虚空裂口x1.5.",

    "[6x3] Loopholes production interval decreases by 7.": "[6x3] 漏洞的生产间隔减短7次点击.",

    "[6x4] Decreases Glitch Power Generators' cost scaling again.": "[6x4] 再次减缓故障能量发生器的价格增长.",

    "[7x1] Glitch power boosts itself gain.": "[7x1] 故障能量加成自身获取速度.",

    "[7x2] Did the game just inflated? Well, boost Void Tear base by another +0.3.": "[7x2] 游戏快膨胀了么? 那么, 再让虚空裂口的底数+0.3吧.",

    "[7x3] Eradications production interval decreases by 10.": "[7x3] 根除的生产间隔减短10次点击.",

    "[7x4] Decreases Glitch Power Generators' cost scaling again.": "[7x4] 再次减缓故障能量发生器的价格增长.",

    "[8x1] Glitches boost Glitch Power gain.": "[8x1] 故障加成故障能量的获取速度.",

    "[8x2] Glitch Power boosts Void Tear base by a bit.": "[8x2] 故障能量小幅度加成虚空裂口的底数.",

    "[8x3] Void Tear effect boosts Glitch Power gain.": "[8x3] 虚空裂口的效果加成故障能量获取速度.",

    "[8x4] Unlocks Minigames & Also raises Glitch gain to ^1.2.": "[8x4] 解锁小游戏 & 同时使得故障获取^1.2.",

    "[9x1] Willpower effect slightly boosts Glitch Power gain.": "[9x1] 意志力小幅度加成故障能量的获取.",

    "[9x2] You get 1.2x more Void Tears from Glitch Power yet again.": "[9x2] 故障能量产生的虚空裂口再次被倍增1.2x.",

    "[9x3] You are close... Void Tears boost Glitch gain very slightly.": "[9x3] 就快到了...虚空裂口极小幅度加成故障获取量.",
    //GU9x4...
    "[9x4] Unlocks": "[9x4] 解锁",
    "that": "那个",
    "upgrade in Reality tab.": "在现实界面的升级.",

    "/ 100 times this run.": "/ 100 次.",
    "A-points.": "A-点数",

    "Achieve 1000 Points at any time of this run.": "达到 1000 点数.",
    "Achieve 10000 Points at any time of this run.": "达到 10000 点数.",
    "Achieve 1e5 Points at any time of this run.": "达到 1e5 点数.",
    "Achieve 2e24 Points at any time of this run! How???!": "达到 2e24 点数! 怎么做到的???!",
    "Achieve 5e46 Points at any time of this run! How???!": "达到 5e46 点数! 怎么做到的???!",
    "Achieve 6.9e69 Points at any time of this run.  Nice.": "达到 6.9e69 点数. 漂亮.",

    "Acquire 145 Faults.": "获得 145 个错误.",
    "Acquire 225 Faults.": "获得 225 个错误.",
    "Added 2 rows of Glitch upgrades and 2 goals.": "增加了2行故障升级和2个目标.",
    "Added a minigame.": "增加了一个小游戏.",
    "Added a minigame. (I'm fed up with making this.": "增加了一个小游戏. (我厌倦了做这个东西.",
    "Added a new mechanism: Glitch Power.": "加入了一个新的机制: 故障能量.",
    "Added a new Prestige Layer.": "加入了一个新的层级.",
    "Added a new Prestige Layer. (This is enough to make a major update.": "加入了一个新的层级 (这足以做一个大重置了吧",
    "Added a new row of Glitch upgrades and a new challenge.": "加入了一行新的故障升级和一个新的挑战.",
    "Added a new row of Glitch upgrades and inflated the game.": "加入了一行新的故障升级并且让游戏膨胀了.",
    "Added a new row of Glitch upgrades.": "加入了一行新的故障升级.",
    "Added another row of Glitch upgrade.": "加入了另一行新的故障升级.",
    "Added another row of Glitch upgrades.": "加入了另一行新的故障升级.",
    "Added Challenges tab and a challenge.": "加入了挑战界面和一个挑战.",
    "Added goal requirements to Glitch upgrades.": "给故障升级添加了目标要求.",
    "Added main mechanisms.": "加入了主要的游戏机制.",
    "Added prompt on completing goals or challenges.": "加入了完成成就和挑战的提示.",
    "Added Save and Reload button.": "加入了存档和重新加载按钮.",
    "Are You A Robot?": "你是个机器人吗?",
    "Balance (mostly nerfs) and minor bug fixes.": "平衡游戏(大部分是削弱)并且修复一些小Bug.",
    "Bug fixes.": "修复Bug.",
    "Buy 2": "购买两个",

    "Buy a Loophole.": "购买一个漏洞.",
    "Buy all Glitch upgrades for free.": "免费购买所有故障升级.",
    "Buy Max": "购买最大",
    "Centiclick": "岑提点击",
    "Challenge": "挑战",
    "Challenge 1": "挑战1",
    "Challenge 2": "挑战2",
    "Challenge 3": "挑战3",
    "Changelog": "更新日志",
    "Click to enter": "点击开始",
    "Clicking on the \"Get Points\" button costs 5 clicks. Glitch Upgrades 2x2 and 3x2 are disabled.": "点击 \"获取点数\" 按钮消耗5次点击次数. 禁用故障升级2x2和3x2.",
    "Collect all those upgrades below to unlock True Meta tab!": "购买所有这些升级来解锁 “真·元界面”",
    "Complete minigame A.": "完成小游戏A.",
    "Complete minigame B.": "完成小游戏B.",
    "Completing challenges gives rewards and unlocks a new row of Glitch upgrades.": "完成挑战给予相应的奖励, 并且解锁新的一行故障升级.",
    "Confirm": "确认",
    "Cost increases and nerfs.": "价格提高并且进行一定的削弱.",
    "Crack": "裂隙",
    "Developed by l319836": "游戏由l319836开发",
    "Endgame.": "终局.",
    "Enjoy the RESET.": "享受从头再来吧.(注:还有内容)",
    "Eradication": "根除",
    "Exit": "退出",
    "Export": "导出",
    "Export to file": "导出到文件",
    "Extra Void Tears are hardcapped at +6.00.": "额外的虚空裂口上限为 +6.00.",
    "extra Void Tears.": "额外的虚空裂口.",
    "Fault": "错误",
    "Glitch Power is generated continuously.": "故障能量可以随时间连续生产.",
    "Glitch Power is resetted on Glitch reset.": "故障能量在故障重置时会被重置.",
    "Glitch Power, translated to a bonus of +": "故障能量, 转化为加成 +",
    "Goals are like achievements: They never resets.": "目标就像成就: 它们不会被故障重置.",
    "Hide Completed": "隐藏已完成的目标",
    "Hide completed goal button and visual effect improvement.": "添加“隐藏已完成的目标”按钮并且改善视觉效果.",
    "Import": "导入",
    "Last Page": "最后一页",
    "Lines of Code (LoC).": "代码行",
    "Loophole": "漏洞",
    "Main": "主页面",
    "Major bug fixes and rebalance, thanks to @ACrazySteve": "修复重大bug并且重平衡, 感谢@ACrazySteve",
    "Major bug fixes. (Thanks to @Crimson406": "修复重大bug. (感谢@Crimson406",
    "Major rebalance and nerfs, because the game inflated.": "大型重平衡和削弱, 因为游戏膨胀了.",
    "Mid-game rebalance.": "游戏中期重平衡.",
    "Minigame A": "小游戏A",
    "Minigame B": "小游戏B",
    "Minor bug fixes and optimizations.": "修复小bug并且优化游戏.",
    "Next Page": "下一页",
    "Obtain +0.5 extra Void Tears from Glitch Power.": "从故障能量处获得 +0.5 的额外虚空裂口.",
    "Obtain +5.86 extra Void Tears from Glitch Power. (just a random number lol": "从故障能量处获得 +5.86 的额外虚空裂口. (这纯粹就是个随机数2333",
    "Obtain 1000 Glitch Power.": "获得1000故障能量",
    "Optimized display & bug fixes.": "优化显示 & 修复bug.",
    "Optimized display.": "优化显示.",
    "Perks": "专精",
    "Play some Minigame B for fun!": "玩小游戏B放松一下!",
    "Points.": "点数.",
    "Power": "能量",
    "Power Generator": "能量发生器",
    "Reality": "现实",
    "Reload": "重新加载",
    "Everything is autobought.": "自动购买所有东西.",
    "Removes the 100 clicks restriction from the game.": "移除只能进行100次点击的限制.",
    "Removes the clicking button. Instead, auto-click once every 50ms.": "移除点击按钮. 每50毫秒自动点击一次来取而代之.",
    "In a Glitched Reality.": "处于故障现实中.",
    "In a Malfunctioning Reality.": "处于失灵现实中.",
    "In a Meta Reality.": "处于元现实中.",
    "In Florena's Reality.": "处于芙雷娜的现实中.",
    "Reward: Decreases production interval of Cracks, Loopholes and Eradications. Glitch gain also gets a x2 boost.": "奖励: 减短裂隙、漏洞、和根除的生产间隔. 同时故障的获取量x2.",
    "Reward: Glitch Upgrades 2x2 and 3x2 are stronger. Buff Glitch Upgrade 6x2 by +1. Also 2x Glitch gain.": "奖励: 故障升级2x2和3x2更强. 故障升级6x2的效果+1. 同时故障的获取量x2.",
    "Reward: Void Tear effect base is improved by a bit. You also get another x2 multiplier to Glitch gain. Isn't that great?": "奖励: 虚空裂口的效果底数小幅度增加. 你同时也获得了2x的故障获取量倍率. 这不是很棒吗?",
    "Save": "存档",
    "Show Completed": "显示已完成的目标",
    "Sometimes you have to deal with some annoying things.": "有些时候你需要处理一些麻烦的东西.",
    "Start": "开始",
    "Start on next run": "下一轮开始",
    "Starting on next run...": "即将在下一轮开始...",
    "Surprise update! (Export & Import": "惊人的更新! (导出 & 导入",
    "System": "系统",
    "TEST MESSAGE": "测试信息",
    "The Color Ring": "色彩环",
    "The Perfect Solution": "完美解法",
    "to Void Tear's base.": "的虚空裂口的底数.",
    "Try to figure out how the game works! (the minigame only works while you are in it.": "试着搞明白这个游戏是怎么运行的! (小游戏只在你进入的时候工作",
    "Typo fixes. (Thanks to @card reshuffled game": "修正说明. (感谢@card reshuffled game",
    "Version": "版本",
    "Visual improvements.": "视觉效果优化",
    "Visual optimizations.": "视觉效果优化",
    "Void Tear": "虚空裂口",
    "Void Tears cannot be bought.": "无法购买虚空裂口.",
    "Wasteless Progression": "无浪费的流程",
    "Willpower effect and Glitch upgrade effects are disabled.": "意志力和故障升级的效果被禁用.",
    "You automatically get 10% of the glitches you gain per second.": "你每秒获得10%重置时将获得的故障.",
    "You have": "你有",
    "You have clicked": "你这轮已经点击了",
    "You will encounter a Glitch reset at 100 clicks.": "你会在第100次点击时触发一次故障重置.",
    "You will face a 0.4x penalty if you are gaining too few points.": "如果获得的点数过少,你会获得x0.4的惩罚.",
    "Your Glitch Power also provides +": "你的故障能量同时也提供了 +",
    "You will never encounter a glitch reset again. Never.":"你永远不会触发故障重置了. 永远.",
    "Completed":"已完成",
    "COMPLETED":"已完成",
    "Extra Void Tears are not hardcapped because of you being in a Malfunctioning Reality!":"额外的虚空裂口的硬上限被移除了, 因为你处于失灵现实中!",
    "This will reset everything so far, but also unlock a new tab & some upgrades.":"这会重置以前的所有内容, 但是也会解锁一个新的页面和一些升级.",
    "RESET":"重置",
    "Click all the vowels (a,e,i,o,u) in the following sentence":"点击所有的元音字母(a,e,i,o,u)",
    "Click all the characters that only appears once in the following word":"点击所有只出现一次的字符",
    "Click all the characters that are not letters or spaces in the following sentence":"点击所有不是字母又不是空格的字符",
    "Click all the uppercase consonants in the following sentence":"点击所有的大写辅音字母",
    "Click all the characters that have an odd ASCII code":"点击所有的ASCII码为奇数的字符",
    "Wrong!":"错误!",
    "Correct!":"正确!",
    "Continue":"继续",
    "Glitch Power is not resetted on Glitch reset thanks to Glitch Upgrade 6x1.":"故障能量因为故障升级6x1不会被重置.",
    "Goal":"目标",
    "Glitches.":"故障.",
    "Glitch":"故障",
    "Willpower.":"意志力.",
    "Effect:":"效果:",
    "Req: In a Glitched Reality.":"要求: 处于故障现实中.",
    "Req: In a Malfunctioning Reality.":"要求: 处于失灵现实中.",
    "Req: In a Meta Reality.":"要求: 处于元现实中.",
    "Req: In Florena's Reality.":"要求: 处于芙蕾娜的现实中.",
    "Minigame progress are kept on any (soft) reset.":"小游戏的进度在任何(软)重置时都不会被重置.",
    "Remove Extra Void Tear's hardcap.":"移除额外虚空裂口的硬上限.",
    "Glitch gain softcap is slightly lifted.":"故障获取量的软上限被小幅度削弱.",
    "Running":"正在进行",
    "Locked by Challenge 2.":"被挑战2禁用.",
    "NOTE: You don't have to play it.":"注意: 你并不需要通过这些.",
    "true":"超脱",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    //现实说明
    "Too many Glitches have made the reality glitched.":"太多的故障使得现实故障了.",
    "This will reset everything, but also unlocks new content.":"这会重置所有东西, 但是也会解锁新内容.",
    "Willpower effect's exponent's exponent is buffed by +0.05 to compensate.":"意志力的效果的“指数的指数”+0.05来补偿这次重置.",
    "Too many Glitches are beginning to break the reality.":"太多的故障已经开始打破现实了.",
    "Willpower effect's exponent's exponent is buffed by +0.05 and Extra Void Tears' hardcap is removed to compensate.":"意志力的效果的“指数的指数”+0.05, 并且移除额外虚空裂口的上限来补偿这次重置.",
    "You have partially melted your reality, mixing it with others.":"你让现实开始融毁了, 使得它与别的现实混在一起.",
    "Willpower effect's exponent's exponent is buffed by +0.05 and Glitch gain softcap is slightly lifted to compensate.":"意志力的效果的“指数的指数”+0.05, 并且小幅度削弱故障获取量的软上限来补偿这次重置.",
    "Your reality is completely destroyed. However, Florena, the Goddess of Reality, invites you into her reality instead. Hope you don't break it :":"你的现实彻底破碎了. 然而, 芙蕾娜, 现实之神, 邀请你去她的现实. 希望你不要打破它了 :",
    "Willpower effect's exponent's exponent is buffed by +0.05 and your minigame progress are kept on any (soft) reset to compensate.":"意志力的效果的“指数的指数”+0.05, 并且永久在(软)重置时保留小游戏进度来补偿这次重置.",
    "You have nowhere to go. But you are still there, in the System of Existence.":"你无处可去. 但你仍然在这, 在“存在”这个系统中.",
    "But have you ever thought that this game might be a minigame of something larger?":"但你想过这个游戏也可能算是一个小游戏或者什么更大的东西?",
    //
    "You are currently in a Glitched Reality.":"你当前处于故障现实中.",
    "You are currently in a Malfunctioning Reality.":"你当前处于失灵现实中.",
    "You are currently in a Meta Reality.":"你当前处于元现实中.",
    "You are currently in Florena's Reality.":"你当前处于芙蕾娜的现实中.",
    //C2...作者怎么想出来的分开一整个名字
    "B": "最佳","est": "组合",
    "F": "","lex": "",
    "C": "","ombination": "",
    //弹出框提示
    "Exported to Clipboard!":"已导出至剪切板!",
    "Exported to file!":"已导出至文件!",
    "Imported from file!":"已从文件导入!",
    "Imported from Clipboard!":"已从剪切板导入!",
    //更新日志
    "Rewrote literally everything.":"重写几乎所有内容.",
    "Break infinity.":"打破无限.",
    "The game is still buggy, please report at once if you find one.":"游戏目前仍然漏洞百出, 如果有bug请立刻报告.",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Currently":"当前",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)$/,
    /^\+([\d\.]+)$/,
    /^\-([\d\.]+)$/,
    /^\x([\d\.]+)$/,
    /^\^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^You have completed (.+) Centi-clicks. Last time you got (.+) Points = (.+) Glitches in 100 clicks.$/, "你已经完成了 $1 次百分点击. 上一轮在100次点击里你获得了 $2 点数 = $3 故障."],
    [/^You get Glitches based on Willpower and Points. If you go Glitch now, you will get (.+) Glitches.$/ , "你基于意志力和点数获得故障点. 如果你现在就进行故障重置, 你将会获得 $1 故障."],
    [/^Gives you (.+) Cracks every (\d+) clicks.$/, "每 $2 次点击给予 $1 个裂隙."],
    [/^Gives you (.+) Faults every (\d+) clicks.$/, "每 $2 次点击给予 $1 个错误."],
    [/^Gives you (.+) Glitch Power every second.$/, "每秒给予 $1 故障能量."],
    [/^Gives you (.+) Loopholes every (\d+) clicks.$/, "每 $2 次点击给予 $1 个裂隙."],
    [/^Gives you (.+) Points every click.$/, "每次点击给予 $1 点数."],
    [/^Buy a Crack for (\d+) Faults.$/, "用 $1 个错误购买一个裂隙."],
    [/^Buy a Fault for ([\d\.,]+) Points.$/, "用 $1 点数购买一个错误."],
    [/^Buy a Loophole for (\d+) Cracks.$/, "用 $1 个裂隙购买一个漏洞."],
    [/^Buy a Void Tear for (.+) Points.$/, "用 $1 点数购买一个虚空裂口."],
    [/^Buy an Eradication for (\d+) Loopholes.$/, "用 $1 个漏洞购买一个根除."],
    [/^Click to get (.+) points.$/, "点击以获得 $1 点数."],
    [/^Buy one for (.+) Glitches.$/, "用 $1 故障购买一个."],
    [/^Increases your Willpower effect's exponent's exponent by (.+). \(based on time$/, "你的意志力的效果的指数的指数 +$1. (基于时间"],
    [/^Multiplies all production by (.+)x.$/, "倍增所有产量 x$1."],
    [/^Page (\d+) of (\d+)$/, "第$1/$2页"],
    [/^You have done ([\d\.,]+) System Resets.$/, "你已经完成了 $1 次系统重置."],
    [/^Your highest Point is (.+). Your highest Glitch gain on one reset is (.+).$/, "你达成的最高点数是 $1. 你故障获取最多的一次重置获得了 $2 故障."],
    [/^Your Willpower gives a (.+)x bonus to Glitch gain.$/, "你的意志力使得故障获取量 x$1."],
    [/^Req: Challenge (\d+) Completed.$/, "要求: 完成挑战$1."],
    [/^You have (\d+) B-points.$/, "你拥有 $1 B-点数."],
    [/^Buy one for (.+) glitches$/, "用 $1 故障购买一个."],
    [/^Goal (\d+)$/, "目标 $1"],
    [/^Goal: (.+) Points.$/, "目标: $1 点数."],
    [/^Cost: (.+) Glitches.$/, "价格: $1 故障."],
    [/^Req: (\d+) Willpower.$/, "要求: $1 意志力."],
    [/^Effect: (.+)$/, "效果: $1"],
    [/^REWARD: (\d+) WP$/, "奖励: $1 意志力"],
    [/^Cost: (.+) LoC.$/, "价格: $1 代码行."],
    [/^indev (.+)$/, "测试版 $1"],
    [/^Goal: (.+) A-points.$/, "目标: $1 A-点数."],
    [/^Goal: (.+) B-points.$/, "目标: $1 B-点数."],
    [/^Version (.+)$/, "版本 $1"],
    [/^Willpower effect's exponent's exponent \+([\d\.]+).$/, "意志力的效果的指数的指数 +$1."],
]);